
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("6228d51a-7041-4585-bcdb-7e9fd662f26f")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("entityframeworkModel", "fk_tblAddresses_tblprofiles1", "tblprofiles", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(profile), "tbladdresses", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(address), True)>
<Assembly: EdmRelationshipAttribute("entityframeworkModel", "fk_tblphonenumbers_tblphonetypes1", "tblphonetypes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(phonetype), "tblphonenumbers", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(phonenumber), True)>
<Assembly: EdmRelationshipAttribute("entityframeworkModel", "fk_tblphonenumbers_tblprofiles1", "tblprofiles", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(profile), "tblphonenumbers", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(phonenumber), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class OnlineContact
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new OnlineContact object using the connection string found in the 'OnlineContact' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=OnlineContact", "OnlineContact")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new OnlineContact object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "OnlineContact")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new OnlineContact object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "OnlineContact")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property addresses() As ObjectSet(Of address)
        Get
            If (_addresses Is Nothing) Then
                _addresses = MyBase.CreateObjectSet(Of address)("addresses")
            End If
            Return _addresses
        End Get
    End Property

    Private _addresses As ObjectSet(Of address)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property phonenumbers() As ObjectSet(Of phonenumber)
        Get
            If (_phonenumbers Is Nothing) Then
                _phonenumbers = MyBase.CreateObjectSet(Of phonenumber)("phonenumbers")
            End If
            Return _phonenumbers
        End Get
    End Property

    Private _phonenumbers As ObjectSet(Of phonenumber)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property phonetypes() As ObjectSet(Of phonetype)
        Get
            If (_phonetypes Is Nothing) Then
                _phonetypes = MyBase.CreateObjectSet(Of phonetype)("phonetypes")
            End If
            Return _phonetypes
        End Get
    End Property

    Private _phonetypes As ObjectSet(Of phonetype)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property profiles() As ObjectSet(Of profile)
        Get
            If (_profiles Is Nothing) Then
                _profiles = MyBase.CreateObjectSet(Of profile)("profiles")
            End If
            Return _profiles
        End Get
    End Property

    Private _profiles As ObjectSet(Of profile)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the addresses EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToaddresses(ByVal address As address)
        MyBase.AddObject("addresses", address)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the phonenumbers EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTophonenumbers(ByVal phonenumber As phonenumber)
        MyBase.AddObject("phonenumbers", phonenumber)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the phonetypes EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTophonetypes(ByVal phonetype As phonetype)
        MyBase.AddObject("phonetypes", phonetype)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the profiles EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToprofiles(ByVal profile As profile)
        MyBase.AddObject("profiles", profile)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="entityframeworkModel", Name:="address")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class address
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new address object.
    ''' </summary>
    ''' <param name="id">Initial value of the ID property.</param>
    ''' <param name="addressLine1">Initial value of the AddressLine1 property.</param>
    ''' <param name="addressLine2">Initial value of the AddressLine2 property.</param>
    ''' <param name="postCode">Initial value of the PostCode property.</param>
    ''' <param name="county">Initial value of the County property.</param>
    ''' <param name="city">Initial value of the City property.</param>
    ''' <param name="country">Initial value of the Country property.</param>
    ''' <param name="fKProfileID">Initial value of the FKProfileID property.</param>
    Public Shared Function Createaddress(id As Global.System.Int32, addressLine1 As Global.System.String, addressLine2 As Global.System.String, postCode As Global.System.String, county As Global.System.String, city As Global.System.String, country As Global.System.String, fKProfileID As Global.System.Int32) As address
        Dim address as address = New address
        address.ID = id
        address.AddressLine1 = addressLine1
        address.AddressLine2 = addressLine2
        address.PostCode = postCode
        address.County = county
        address.City = city
        address.Country = country
        address.FKProfileID = fKProfileID
        Return address
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.Int32
        Get
            Return _ID
        End Get
        Set
            If (_ID <> Value) Then
                OnIDChanging(value)
                ReportPropertyChanging("ID")
                _ID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ID")
                OnIDChanged()
            End If
        End Set
    End Property

    Private _ID As Global.System.Int32
    Private Partial Sub OnIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AddressLine1() As Global.System.String
        Get
            Return _AddressLine1
        End Get
        Set
            OnAddressLine1Changing(value)
            ReportPropertyChanging("AddressLine1")
            _AddressLine1 = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("AddressLine1")
            OnAddressLine1Changed()
        End Set
    End Property

    Private _AddressLine1 As Global.System.String
    Private Partial Sub OnAddressLine1Changing(value As Global.System.String)
    End Sub

    Private Partial Sub OnAddressLine1Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AddressLine2() As Global.System.String
        Get
            Return _AddressLine2
        End Get
        Set
            OnAddressLine2Changing(value)
            ReportPropertyChanging("AddressLine2")
            _AddressLine2 = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("AddressLine2")
            OnAddressLine2Changed()
        End Set
    End Property

    Private _AddressLine2 As Global.System.String
    Private Partial Sub OnAddressLine2Changing(value As Global.System.String)
    End Sub

    Private Partial Sub OnAddressLine2Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property PostCode() As Global.System.String
        Get
            Return _PostCode
        End Get
        Set
            OnPostCodeChanging(value)
            ReportPropertyChanging("PostCode")
            _PostCode = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("PostCode")
            OnPostCodeChanged()
        End Set
    End Property

    Private _PostCode As Global.System.String
    Private Partial Sub OnPostCodeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPostCodeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property County() As Global.System.String
        Get
            Return _County
        End Get
        Set
            OnCountyChanging(value)
            ReportPropertyChanging("County")
            _County = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("County")
            OnCountyChanged()
        End Set
    End Property

    Private _County As Global.System.String
    Private Partial Sub OnCountyChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCountyChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property City() As Global.System.String
        Get
            Return _City
        End Get
        Set
            OnCityChanging(value)
            ReportPropertyChanging("City")
            _City = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("City")
            OnCityChanged()
        End Set
    End Property

    Private _City As Global.System.String
    Private Partial Sub OnCityChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCityChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Country() As Global.System.String
        Get
            Return _Country
        End Get
        Set
            OnCountryChanging(value)
            ReportPropertyChanging("Country")
            _Country = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Country")
            OnCountryChanged()
        End Set
    End Property

    Private _Country As Global.System.String
    Private Partial Sub OnCountryChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCountryChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property FKProfileID() As Global.System.Int32
        Get
            Return _FKProfileID
        End Get
        Set
            OnFKProfileIDChanging(value)
            ReportPropertyChanging("FKProfileID")
            _FKProfileID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("FKProfileID")
            OnFKProfileIDChanged()
        End Set
    End Property

    Private _FKProfileID As Global.System.Int32
    Private Partial Sub OnFKProfileIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnFKProfileIDChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("entityframeworkModel", "fk_tblAddresses_tblprofiles1", "tblprofiles")>
    Public Property profile() As profile
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of profile)("entityframeworkModel.fk_tblAddresses_tblprofiles1", "tblprofiles").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of profile)("entityframeworkModel.fk_tblAddresses_tblprofiles1", "tblprofiles").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property profileReference() As EntityReference(Of profile)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of profile)("entityframeworkModel.fk_tblAddresses_tblprofiles1", "tblprofiles")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of profile)("entityframeworkModel.fk_tblAddresses_tblprofiles1", "tblprofiles", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="entityframeworkModel", Name:="phonenumber")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class phonenumber
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new phonenumber object.
    ''' </summary>
    ''' <param name="id">Initial value of the ID property.</param>
    ''' <param name="number">Initial value of the Number property.</param>
    ''' <param name="fKPhoneTypeID">Initial value of the FKPhoneTypeID property.</param>
    ''' <param name="fKProfileID">Initial value of the FKProfileID property.</param>
    Public Shared Function Createphonenumber(id As Global.System.Int32, number As Global.System.String, fKPhoneTypeID As Global.System.Int32, fKProfileID As Global.System.Int32) As phonenumber
        Dim phonenumber as phonenumber = New phonenumber
        phonenumber.ID = id
        phonenumber.Number = number
        phonenumber.FKPhoneTypeID = fKPhoneTypeID
        phonenumber.FKProfileID = fKProfileID
        Return phonenumber
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.Int32
        Get
            Return _ID
        End Get
        Set
            If (_ID <> Value) Then
                OnIDChanging(value)
                ReportPropertyChanging("ID")
                _ID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ID")
                OnIDChanged()
            End If
        End Set
    End Property

    Private _ID As Global.System.Int32
    Private Partial Sub OnIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Number() As Global.System.String
        Get
            Return _Number
        End Get
        Set
            OnNumberChanging(value)
            ReportPropertyChanging("Number")
            _Number = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Number")
            OnNumberChanged()
        End Set
    End Property

    Private _Number As Global.System.String
    Private Partial Sub OnNumberChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNumberChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property FKPhoneTypeID() As Global.System.Int32
        Get
            Return _FKPhoneTypeID
        End Get
        Set
            OnFKPhoneTypeIDChanging(value)
            ReportPropertyChanging("FKPhoneTypeID")
            _FKPhoneTypeID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("FKPhoneTypeID")
            OnFKPhoneTypeIDChanged()
        End Set
    End Property

    Private _FKPhoneTypeID As Global.System.Int32
    Private Partial Sub OnFKPhoneTypeIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnFKPhoneTypeIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property FKProfileID() As Global.System.Int32
        Get
            Return _FKProfileID
        End Get
        Set
            OnFKProfileIDChanging(value)
            ReportPropertyChanging("FKProfileID")
            _FKProfileID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("FKProfileID")
            OnFKProfileIDChanged()
        End Set
    End Property

    Private _FKProfileID As Global.System.Int32
    Private Partial Sub OnFKProfileIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnFKProfileIDChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("entityframeworkModel", "fk_tblphonenumbers_tblphonetypes1", "tblphonetypes")>
    Public Property phonetype() As phonetype
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of phonetype)("entityframeworkModel.fk_tblphonenumbers_tblphonetypes1", "tblphonetypes").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of phonetype)("entityframeworkModel.fk_tblphonenumbers_tblphonetypes1", "tblphonetypes").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property phonetypeReference() As EntityReference(Of phonetype)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of phonetype)("entityframeworkModel.fk_tblphonenumbers_tblphonetypes1", "tblphonetypes")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of phonetype)("entityframeworkModel.fk_tblphonenumbers_tblphonetypes1", "tblphonetypes", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("entityframeworkModel", "fk_tblphonenumbers_tblprofiles1", "tblprofiles")>
    Public Property profile() As profile
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of profile)("entityframeworkModel.fk_tblphonenumbers_tblprofiles1", "tblprofiles").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of profile)("entityframeworkModel.fk_tblphonenumbers_tblprofiles1", "tblprofiles").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property profileReference() As EntityReference(Of profile)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of profile)("entityframeworkModel.fk_tblphonenumbers_tblprofiles1", "tblprofiles")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of profile)("entityframeworkModel.fk_tblphonenumbers_tblprofiles1", "tblprofiles", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="entityframeworkModel", Name:="phonetype")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class phonetype
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new phonetype object.
    ''' </summary>
    ''' <param name="id">Initial value of the ID property.</param>
    ''' <param name="name">Initial value of the Name property.</param>
    Public Shared Function Createphonetype(id As Global.System.Int32, name As Global.System.String) As phonetype
        Dim phonetype as phonetype = New phonetype
        phonetype.ID = id
        phonetype.Name = name
        Return phonetype
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.Int32
        Get
            Return _ID
        End Get
        Set
            If (_ID <> Value) Then
                OnIDChanging(value)
                ReportPropertyChanging("ID")
                _ID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ID")
                OnIDChanged()
            End If
        End Set
    End Property

    Private _ID As Global.System.Int32
    Private Partial Sub OnIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Name() As Global.System.String
        Get
            Return _Name
        End Get
        Set
            OnNameChanging(value)
            ReportPropertyChanging("Name")
            _Name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Name")
            OnNameChanged()
        End Set
    End Property

    Private _Name As Global.System.String
    Private Partial Sub OnNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNameChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("entityframeworkModel", "fk_tblphonenumbers_tblphonetypes1", "tblphonenumbers")>
     Public Property phonenumbers() As EntityCollection(Of phonenumber)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of phonenumber)("entityframeworkModel.fk_tblphonenumbers_tblphonetypes1", "tblphonenumbers")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of phonenumber)("entityframeworkModel.fk_tblphonenumbers_tblphonetypes1", "tblphonenumbers", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="entityframeworkModel", Name:="profile")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class profile
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new profile object.
    ''' </summary>
    ''' <param name="id">Initial value of the ID property.</param>
    ''' <param name="firstName">Initial value of the FirstName property.</param>
    ''' <param name="lastName">Initial value of the LastName property.</param>
    ''' <param name="email">Initial value of the Email property.</param>
    ''' <param name="nickName">Initial value of the NickName property.</param>
    Public Shared Function Createprofile(id As Global.System.Int32, firstName As Global.System.String, lastName As Global.System.String, email As Global.System.String, nickName As Global.System.String) As profile
        Dim profile as profile = New profile
        profile.ID = id
        profile.FirstName = firstName
        profile.LastName = lastName
        profile.Email = email
        profile.NickName = nickName
        Return profile
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.Int32
        Get
            Return _ID
        End Get
        Set
            If (_ID <> Value) Then
                OnIDChanging(value)
                ReportPropertyChanging("ID")
                _ID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ID")
                OnIDChanged()
            End If
        End Set
    End Property

    Private _ID As Global.System.Int32
    Private Partial Sub OnIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property FirstName() As Global.System.String
        Get
            Return _FirstName
        End Get
        Set
            OnFirstNameChanging(value)
            ReportPropertyChanging("FirstName")
            _FirstName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("FirstName")
            OnFirstNameChanged()
        End Set
    End Property

    Private _FirstName As Global.System.String
    Private Partial Sub OnFirstNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFirstNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property LastName() As Global.System.String
        Get
            Return _LastName
        End Get
        Set
            OnLastNameChanging(value)
            ReportPropertyChanging("LastName")
            _LastName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("LastName")
            OnLastNameChanged()
        End Set
    End Property

    Private _LastName As Global.System.String
    Private Partial Sub OnLastNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLastNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Email() As Global.System.String
        Get
            Return _Email
        End Get
        Set
            OnEmailChanging(value)
            ReportPropertyChanging("Email")
            _Email = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Email")
            OnEmailChanged()
        End Set
    End Property

    Private _Email As Global.System.String
    Private Partial Sub OnEmailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnEmailChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property NickName() As Global.System.String
        Get
            Return _NickName
        End Get
        Set
            OnNickNameChanging(value)
            ReportPropertyChanging("NickName")
            _NickName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("NickName")
            OnNickNameChanged()
        End Set
    End Property

    Private _NickName As Global.System.String
    Private Partial Sub OnNickNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNickNameChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("entityframeworkModel", "fk_tblAddresses_tblprofiles1", "tbladdresses")>
     Public Property addresses() As EntityCollection(Of address)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of address)("entityframeworkModel.fk_tblAddresses_tblprofiles1", "tbladdresses")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of address)("entityframeworkModel.fk_tblAddresses_tblprofiles1", "tbladdresses", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("entityframeworkModel", "fk_tblphonenumbers_tblprofiles1", "tblphonenumbers")>
     Public Property phonenumbers() As EntityCollection(Of phonenumber)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of phonenumber)("entityframeworkModel.fk_tblphonenumbers_tblprofiles1", "tblphonenumbers")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of phonenumber)("entityframeworkModel.fk_tblphonenumbers_tblprofiles1", "tblphonenumbers", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region


